# Generated by Django 4.0.3 on 2022-03-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='price',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='coin',
            name='rank',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
